### ISSUE TITLE
Error `over quota` when going to https://staging.bamzooka.com/a/workspaces/4/checklists/19?cardId=59

### ISSUE THREAD

**Issue by supercobra** [bamzooka/bamzooka#255]
https://staging.bamzooka.com/a/workspaces/4/checklists/19?cardId=59

## UI

![image](https://user-images.githubusercontent.com/678907/136244828-2ce73f52-9536-4034-9eb2-160cef5e2e42.png)

## Console

![image](https://user-images.githubusercontent.com/678907/136245155-9dc69f7e-3a8c-45d7-9c8d-7671309010a1.png)

**Comment by Mubramaj** [comment]
Fixed by changing the number of requests in NGINX config
